lib/modest_greeter_web/router.ex
defmodule ModestGreeterWeb.Router do
  use ModestGreeterWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", ModestGreeterWeb do
    pipe_through :browser

    get "/", TopController, :index
    get "/about", TopController, :about
    get "/hello", HelloController, :show
    get "/hello/:name", HelloController, :show
  end
end

lib/modest_greeter/application.ex
defmodule ModestGreeter.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the endpoint when the application starts
      ModestGreeterWeb.Endpoint
      # Starts a worker by calling: ModestGreeter.Worker.start_link(arg)
      # {ModestGreeter.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: ModestGreeter.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ModestGreeterWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/modest_greeter_web/controllers/hello_controller.ex
defmodule ModestGreeterWeb.HelloController do
  use ModestGreeterWeb, :controller

  def show(conn, params) do
    render conn, "show.html", name: params["name"] || "world"
  end
end

lib/modest_greeter_web/controllers/top_controller.ex
defmodule ModestGreeterWeb.TopController do
  use ModestGreeterWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def about(conn, _params) do
    render conn, "about.html"
  end
end

lib/modest_greeter_web/views/error_view.ex
defmodule ModestGreeterWeb.ErrorView do
  use ModestGreeterWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/modest_greeter_web/views/hello_view.ex
defmodule ModestGreeterWeb.HelloView do
  use ModestGreeterWeb, :view
  
  def document_title(assigns) do
    "ModestGreeter (#{assigns.name})"
  end
end

lib/modest_greeter_web/views/layout_view.ex
defmodule ModestGreeterWeb.LayoutView do
  use ModestGreeterWeb, :view
end

lib/modest_greeter_web/views/top_view.ex
defmodule ModestGreeterWeb.TopView do
  use ModestGreeterWeb, :view

  def document_title(assigns) do
    case assigns.view_template do
      "about.html" -> "ModestGreeter - このサイトについて"
      _ -> "ModestGreeter"
    end
  end
end

lib/modest_greeter_web/templates/hello/show.html.eex
<div class="card m-3">
  <%= tag :img,
    src: Routes.static_path(@conn, "/images/modest_greeter.svg"),
    alt: "Robot", style: "width: 100%; max-width: 375px",
    class: "card-image-top mx-auto" %>
  <div class="card-body text-white bg-success">
    <p class="card-text lead">
      <i class="far fa-smile"></i>
      Hello, <%= @name %>!
    </p>
  </div>
</div>

lib/modest_greeter_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= @view_module.document_title assigns %></title>
    <%= tag :link, rel: "stylesheet",
      href: Routes.static_path(@conn, "/css/app.css") %>
    <%= tag :link, rel: "shortcut icon", type: "image/x-icon",
      href: Routes.static_path(@conn, "/images/modest_greeter.ico") %>
    <%= tag :link, rel: "apple-touch-icon", type: "image/x-icon",
      href: Routes.static_path(@conn, "/images/modest_greeter256.png") %>
  </head>
  <body>
    <header>
      <h1><%= link "ModestGreeter",
        to: Routes.top_path(@conn, :index, []) %></h1>
    </header>
    <main>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <footer>
      &copy; 2019 Oiax Inc.
    </footer>
      <%= content_tag :script, "",
        src: Routes.static_path(@conn, "/js/app.js") %>
  </body>
</html>

lib/modest_greeter_web/templates/top/about.html.eex
<div class="m-3">
  <h1>このサイトについて</h1>
  <p>ModestGreeter は『Elixir/Phoenix 初級①』の学習用 Phoenix アプリです。</p>
</div>

lib/modest_greeter_web/templates/top/index.html.eex
<%
  names = ~w(Alice Bob Charlie)
%>
<div class="jumbotron m-3">
  <h1 class="display-3"><%= document_title(assigns) %></h1>
  <p class="lead">ModestGreeter へようこそ！</p>
  <hr>
  <p><%= link "このサイトについて",
    to: Routes.top_path(@conn, :about, []) %></p>
</div>
<nav class="nav justify-content-center mb-3">
  <%= for name <- names do %>
    <%= link name, to: Routes.hello_path(@conn, :show, name, []),
      class: "nav-link" %>
  <% end %>
</nav>